task_tracker/config/routes.rb
Rails.application.routes.draw do
  root to: redirect('/tasks')
  get '/logout' => 'main#logout', as: :logout

  get '/auth/:provider/callback' => 'main#callback'
  resources :tasks, except: [:delete, :edit, :update] do
    post :close, on: :member
    collection do
      get :all
      post :assign_all
    end
  end

  get 'login' => 'main#login', as: :login
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

task_tracker/app/models/role.rb
class Role < ApplicationRecord
end

task_tracker/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user, optional: true
  enum status: { open: 'open', closed: 'closed' }

  validates :title, :description, presence: true

  scope :unassigned, -> { where(user_id: nil) }

end

task_tracker/app/models/user.rb
class User < ApplicationRecord
  has_many :tasks

  validates :email, presence: true, uniqueness: true
end

task_tracker/app/controllers/main_controller.rb
class MainController < ApplicationController
  skip_before_action :check_auth

  def index
    redirect_to tasks_path if user_logged_in?
  end

  def callback
    auth_info = request.env['omniauth.auth']
    if auth_info.present?
      user_params = {
        username: auth_info.dig('info', 'full_name'),
        email: auth_info.dig('info', 'email'),
        role: auth_info.dig('info', 'role'),
        public_id: auth_info.dig('info', 'public_id'),
        active: auth_info.dig('info', 'active'),
        token: auth_info.dig('credentials', 'token'),
        token_expires_at: Time.at(auth_info.dig('credentials', 'expires_at')),
      }.compact
      user = User.find_by(public_id: user_params[:public_id])
      if user.present?
        user.update(active: auth_info.dig('info', 'active'),
                    token: auth_info.dig('credentials', 'token'),
                    token_expires_at: Time.at(auth_info.dig('credentials', 'expires_at')))
        update_session_params(auth_info)
        redirect_to tasks_path
      else
        User.create(user_params)
        update_session_params(auth_info)
        redirect_to tasks_path
      end
    else
      render json: {error: 'fail'}
    end
  end

  def logout
    session.destroy
    redirect_to 'http://localhost:3001/accounts/me'
  end

  private
  def update_session_params(auth_info)
    session[:user] = auth_info.dig('info', 'public_id')
    session[:token] = auth_info.dig('credentials', 'token')
    session[:token_expires_at] = auth_info.dig('credentials', 'expires_at')
  end

  def login
    redirect_to ENV['AUTH_URL']
  end

end

task_tracker/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :create

  def create
    @user = User.find_or_create_from_auth_hash(auth_hash)
    self.current_user = @user
    redirect_to '/'
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

task_tracker/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  def index
    @tasks = current_user.tasks.open
  end

  def all
    # очень неоптимально, но для попугов сойдет
    @tasks = Task.all.order(:status, :created_at).map { |task| TaskPresenter.new(task) }
    @button = AssignAllTasksPresenter.new(current_user, view_context)
  end

  def assign_all
    return error!(status: 403) unless TaskPolicy.new(current_user).can_assign?

    tasks = Task.open
    Tasks::AssignAll.call(tasks, User.all)
    redirect_to all_tasks_path
  end

  def close
    task = Task.find(params[:id])
    return error!(status: 403) unless TaskPolicy.new(current_user).can_close?(task)

    Tasks::Close.call(task)
    redirect_to tasks_path
  end

  def show
    @task = TaskPresenter.new(@task)
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :user_id, :status)
  end
end

task_tracker/app/helpers/tasks_helper.rb
module TasksHelper
end

task_tracker/app/helpers/users_helper.rb
module UsersHelper
end

task_tracker/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PopugJira</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <%= link_to 'PopugJira', tasks_path, class: 'navbar-brand'  %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'All Tasks', all_tasks_path, class: 'nav-link'  %>
          </li>
          <li class="nav-item">
            <%= link_to 'My tasks', tasks_path, class: 'nav-link' %>
          </li>
        </ul>

      </div>
      <ul class="navbar-nav mr-lg-2">
        <li class="nav-item ">
          <%= link_to 'Выход', logout_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

task_tracker/app/views/main/index.html.erb
<h1>You are not logged in</h1>

<%= link_to 'Login', login_path %>

task_tracker/app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

task_tracker/app/views/tasks/all.html.erb
<p id="notice"><%= notice %></p>

<h1>All Tasks</h1>

<div class="row">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2">
        <%= link_to 'New Task', new_task_path, class: 'btn btn-light' %>
      </div>
      <div class="offset-md-7 col-md-3">

        <%= @button.button %>
      </div>
    </div>
  </div>
</div>
<table class="table">
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>User</th>
    <th>Status</th>
  </tr>
  </thead>

  <tbody>
  <% @tasks.each do |task| %>
    <tr>
      <td><%= link_to task.title, task %></td>
      <td><%= task.description %></td>
      <td><%= task.task_user %></td>
      <td><%= task.status %></td>
    </tr>
  <% end %>
  </tbody>
</table>

task_tracker/app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

task_tracker/app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Me</h1>
<%= @current_user.as_json %>

<h1>My Tasks</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Status</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= link_to task.title, task %></td>
        <td><%= task.description %></td>
        <td><%= task.status %></td>
        <td><%= link_to 'Close task', close_task_path(task.id), class: 'btn btn-sm btn-light', method: :post %></td>
      </tr>
    <% end %>
  </tbody>
</table>

task_tracker/app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

task_tracker/app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @task.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @task.task_user %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<%= link_to 'Back', tasks_path %>